version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: status_page
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  gamma:
    image: orbsnetwork/gamma:experimental
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
